name: ci

on:
  push:
    tags:
      - '*.**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Release SDKs
        run: npx fern-api release ${{ github.event.release.tag_name }} --log-level debug
