name: ci

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Setup Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Print Version
        env:
          TERM: dumb
        run: |
          ./gradlew --version
          echo "VERSION=$(./gradlew printVersion --quiet)" >> $GITHUB_ENV

      - name: Release SDKs
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TERM: dumb
        run: |
          npm config set @fern-api:registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken "${{ env.NPM_TOKEN }}"
          echo "${{ env.VERSION }}"
          npx @fern-api/fern-api-dev release "${{ env.VERSION }}" --log-level debug
